export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const SET_EDIT_JOB = 'SET_EDIT_JOB';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const APPLY_TO_JOB_BEGIN = 'APPLY_TO_JOB_BEGIN';
export const APPLY_TO_JOB_SUCCESS = 'APPLY_TO_JOB_SUCCESS';
export const APPLY_TO_JOB_ERROR = 'APPLY_TO_JOB_ERROR';

export const GET_PUBLIC_JOBS_BEGIN = 'GET_PUBLIC_JOBS_BEGIN';
export const GET_PUBLIC_JOBS_SUCCESS = 'GET_PUBLIC_JOBS_SUCCESS';

export const GET_APPLICATIONS_BEGIN = 'GET_APPLICATIONS_BEGIN';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';

export const UPDATE_APPLICATION_STATUS_BEGIN = 'UPDATE_APPLICATION_STATUS_BEGIN';
export const UPDATE_APPLICATION_STATUS_SUCCESS = 'UPDATE_APPLICATION_STATUS_SUCCESS';

export const GET_PREDICTED_FIT_BEGIN = 'GET_PREDICTED_FIT_BEGIN';
export const GET_PREDICTED_FIT_SUCCESS = 'GET_PREDICTED_FIT_SUCCESS';
export const GET_PREDICTED_FIT_ERROR = 'GET_PREDICTED_FIT_ERROR';